name: PlayerCache
description: Cache a mapping of player names and player unique ids for other plugins.
author: StarTux
version: "0.1"
api: ["1.0.0"]
website: https://cavetale.com
main: com.winthier.playercache.PlayerCachePlugin
depend: [ SQL, GenericEvents ]
commands:
  playercache:
    description: Admin interface
    permission: playercache.playercache
    usage: |-
      /playercache reload - Reload database
      /playercache uuid <name> - get UUID for name
      /playercache name <uuid> - get name for UUID
      /playercache match <pattern> - match player names
permissions:
  playercache.playercache:
    description: Use the admin interface
    default: op
